import { ArrowLeftIcon, PlayIcon } from "@radix-ui/react-icons";
import { useState } from "react";
import "./eventDetail.css";

export type DetailStat = { home: number; away: number };
type FootballPlayer = { number: number; name: string; position: "门将" | "后卫" | "中场" | "前锋"; value: string; substitutedAt?: string; seed: number };
type BasketballPlayer = { number: number; name: string; points: number; rebounds: number; assists: number; made: number; attempted: number; seed: number };
type FootballTeamLineup = { formation: string; coach: { name: string; seed: number }; starters: FootballPlayer[]; substitutes: FootballPlayer[] };
export type EventDetailPayload = { statistics?: Record<string, DetailStat>; footballLineup?: { home: FootballTeamLineup; away: FootballTeamLineup }; basketballLineup?: { home: BasketballPlayer[]; away: BasketballPlayer[] } };
type QuarterScore = { quarter: number; home: number; away: number };
export type EventDetailEvent = { id: string; sport: "football" | "basketball"; league: string; startTime: string; status: "live" | "upcoming" | "finished"; stage?: string; home: { name: string; score?: number }; away: { name: string; score?: number }; halftimeScore?: { home: number; away: number } | null; quarterScores?: QuarterScore[]; detail?: EventDetailPayload };

const footballStatLabels: Array<[string, string, boolean?]> = [["redCards", "红牌"], ["yellowCards", "黄牌"], ["corners", "角球"], ["penalties", "点球"], ["shotsOnTarget", "射正"], ["shotsOffTarget", "射偏"], ["attacks", "进攻"], ["dangerousAttacks", "危险进攻"], ["possession", "控球率", true]];
const basketballStatLabels: Array<[string, string, boolean?]> = [["threePointersMade", "3分球"], ["twoPointersMade", "2分球"], ["freeThrowsMade", "罚球"], ["timeoutsRemaining", "剩余暂停"], ["fouls", "犯规"], ["freeThrowPercentage", "罚球命中率", true], ["totalTimeouts", "总暂停"]];
const avatarPositions = ["0 0", "50% 0", "100% 0", "0 50%", "50% 50%", "100% 50%", "0 100%", "50% 100%", "100% 100%"];
const asset = (file: string) => `${import.meta.env.BASE_URL}assets/${file}`;

const footballNames = ["Ederson", "Walker", "Rúben Dias", "Gvardiol", "Ake", "Rodri", "Bernardo", "Foden", "Doku", "Haaland", "Savinho", "Ortega", "Stones", "Kovačić", "Grealish", "Alvarez"];
const arsenalNames = ["Raya", "White", "Saliba", "Gabriel", "Timber", "Rice", "Ødegaard", "Havertz", "Saka", "Martinelli", "Jesus", "Neto", "Kiwior", "Jorginho", "Trossard", "Nwaneri"];
const basketballNames = ["LeBron James", "Anthony Davis", "Austin Reaves", "D'Angelo Russell", "Rui Hachimura", "Gabe Vincent", "Jarred Vanderbilt", "Max Christie"];
const warriorsNames = ["Stephen Curry", "Jimmy Butler", "Draymond Green", "Jonathan Kuminga", "Brandin Podziemski", "Buddy Hield", "Moses Moody", "Trayce Jackson-Davis"];

function footballPlayers(names: string[], seed: number): FootballPlayer[] {
  const positions: FootballPlayer["position"][] = ["门将", "后卫", "后卫", "后卫", "后卫", "中场", "中场", "中场", "前锋", "前锋", "前锋", "门将", "后卫", "中场", "前锋", "前锋"];
  return names.map((name, index) => ({ number: index === 0 ? 1 : index + 2, name, position: positions[index], value: `€${["95M", "65M", "85M", "48M", "40M", "120M", "70M", "110M", "90M", "180M", "75M", "18M", "52M", "60M", "78M", "45M"][index]}`, substitutedAt: index === 12 ? "68' 替补上场" : index === 14 ? "76' 替补上场" : undefined, seed: seed + index }));
}

function basketballPlayers(names: string[], seed: number): BasketballPlayer[] {
  return names.map((name, index) => ({ number: [23, 3, 15, 1, 28, 7, 2, 20][index], name, points: Math.max(4, 28 - index * 3), rebounds: Math.max(1, 8 - (index % 5)), assists: Math.max(0, 7 - (index % 4)), made: Math.max(2, 10 - index), attempted: 18 - Math.min(index, 5), seed: seed + index }));
}

export function makeEventDetail(sport: "football" | "basketball", status: "live" | "upcoming" | "finished", seed: number): EventDetailPayload {
  if (sport === "football") return {
    statistics: status === "upcoming" ? undefined : { redCards: { home: 0, away: 1 }, yellowCards: { home: 2, away: 4 }, corners: { home: 6, away: 3 }, penalties: { home: 1, away: 0 }, shotsOnTarget: { home: 8, away: 4 }, shotsOffTarget: { home: 5, away: 7 }, attacks: { home: 118, away: 93 }, dangerousAttacks: { home: 62, away: 41 }, possession: { home: 58, away: 42 } },
    footballLineup: { home: { formation: seed % 2 ? "4-3-3" : "4-2-3-1", coach: { name: "Pep Guardiola", seed: seed + 1 }, starters: footballPlayers(footballNames, seed), substitutes: footballPlayers(footballNames.slice(11), seed + 11) }, away: { formation: seed % 2 ? "4-4-2" : "4-3-3", coach: { name: "Mikel Arteta", seed: seed + 5 }, starters: footballPlayers(arsenalNames, seed + 5), substitutes: footballPlayers(arsenalNames.slice(11), seed + 16) } },
  };
  return {
    statistics: status === "upcoming" ? undefined : { threePointersMade: { home: 12, away: 9 }, twoPointersMade: { home: 24, away: 27 }, freeThrowsMade: { home: 18, away: 15 }, timeoutsRemaining: { home: 2, away: 3 }, fouls: { home: 5, away: 7 }, freeThrowPercentage: { home: 84, away: 76 }, totalTimeouts: { home: 7, away: 7 } },
    basketballLineup: { home: basketballPlayers(basketballNames, seed), away: basketballPlayers(warriorsNames, seed + 4) },
  };
}

function TeamCrest({ name }: { name: string }) { return <img className="detail-crest" src={asset("club-crest.png")} alt={`${name} logo`} />; }
function PersonAvatar({ seed, className = "" }: { seed: number; className?: string }) { return <span className={`detail-person-avatar ${className}`} style={{ backgroundImage: `url(${asset("service-avatars-grid.png")})`, backgroundPosition: avatarPositions[seed % avatarPositions.length] }} />; }
function stageOf(event: EventDetailEvent) { return event.status === "upcoming" ? event.startTime : event.status === "finished" ? "完场" : event.stage ?? "进行中"; }
function scoreOf(event: EventDetailEvent) { return event.status === "upcoming" ? "VS" : `${event.home.score ?? 0} : ${event.away.score ?? 0}`; }

function ViewModeSwitcher({ mode, setMode }: { mode: "animation" | "scoreboard"; setMode: (mode: "animation" | "scoreboard") => void }) { return <div className="event-view-switcher"><button className={mode === "animation" ? "active" : ""} onClick={() => setMode("animation")}>动画</button><button className={mode === "scoreboard" ? "active" : ""} onClick={() => setMode("scoreboard")}>比分</button></div>; }
function halftimeScoreOf(event: EventDetailEvent) { return event.sport === "football" && event.status !== "upcoming" ? event.halftimeScore : undefined; }
function periodLabel(quarter: number) { return quarter <= 4 ? `Q${quarter}` : quarter === 5 ? "OT" : `OT${quarter - 4}`; }
function BasketballScoreTable({ event }: { event: EventDetailEvent }) { const actualPeriods = event.quarterScores ?? []; const finalQuarter = Math.max(4, ...actualPeriods.map((item) => item.quarter)); const periods = Array.from({ length: finalQuarter }, (_, index) => index + 1); const latestLiveQuarter = event.status === "live" ? actualPeriods.reduce((latest, item) => Math.max(latest, item.quarter), 0) : 0; const valueFor = (side: "home" | "away", quarter: number) => actualPeriods.find((item) => item.quarter === quarter)?.[side] ?? "-"; const totalFor = (side: "home" | "away") => event.status === "upcoming" ? "-" : event[side].score ?? "-"; const columns = { gridTemplateColumns: `64px repeat(${periods.length + 1}, 29px)` }; return <div className="detail-basketball-score-table" aria-label="各节比分"><div className="detail-basketball-score-row detail-basketball-score-head" style={columns}><span /><>{periods.map((quarter) => <b key={quarter} className={quarter === latestLiveQuarter ? "current-period" : ""}>{periodLabel(quarter)}</b>)}</><b className="total-column">总</b></div>{(["home", "away"] as const).map((side) => <div className="detail-basketball-score-row" style={columns} key={side}><strong>{event[side].name}</strong><>{periods.map((quarter) => { const value = valueFor(side, quarter); return <span key={quarter} className={value === "-" ? "not-started" : quarter === latestLiveQuarter ? "current-period" : ""}>{value}</span>; })}</><b className="total-column">{totalFor(side)}</b></div>)}</div>; }
function Scoreboard({ event }: { event: EventDetailEvent }) { const halftimeScore = halftimeScoreOf(event); return <div className={`event-scoreboard ${event.sport === "basketball" ? "detail-basketball-scoreboard" : "football-scoreboard"}`}><span className="event-league-name">{event.league}</span><b className={event.status === "live" ? "event-status-live" : ""}>{stageOf(event)}</b><div className="event-score-teams"><div><TeamCrest name={event.home.name} /><strong>{event.home.name}</strong></div><div className="scoreboard-score"><em>{scoreOf(event)}</em>{halftimeScore && <small>半场 {halftimeScore.home} : {halftimeScore.away}</small>}</div><div><TeamCrest name={event.away.name} /><strong>{event.away.name}</strong></div></div>{event.sport === "basketball" && <BasketballScoreTable event={event} />}</div>; }
function EventVisualHeader({ event, onBack }: { event: EventDetailEvent; onBack: () => void }) { const [mode, setMode] = useState<"animation" | "scoreboard">("animation"); return <header className={`event-visual event-visual-${event.sport} ${mode === "scoreboard" ? "is-scoreboard" : ""}`}><img src={asset(event.sport === "football" ? "event-football-pitch.svg" : "event-basketball-court.svg")} alt={event.sport === "football" ? "足球场景" : "篮球场景"} /><div className="event-visual-shade" /><button className="event-visual-back" aria-label="返回" onClick={onBack}><ArrowLeftIcon /></button><ViewModeSwitcher mode={mode} setMode={setMode} />{mode === "scoreboard" && <Scoreboard event={event} />}</header>; }

function StatisticRow({ label, value, isPercentage }: { label: string; value: DetailStat; isPercentage?: boolean }) { const max = isPercentage ? 100 : Math.max(value.home, value.away, 1); const homeWidth = value.home / max * 50; const awayWidth = value.away / max * 50; const homeLead = value.home > value.away; const awayLead = value.away > value.home; const format = (number: number) => isPercentage ? `${number}%` : number; return <article className="statistic-row"><div className="statistic-copy"><b>{format(value.home)}</b><span>{label}</span><b>{format(value.away)}</b></div><div className="statistic-bars"><i className={homeLead ? "lead statistic-home-bar" : "statistic-home-bar"} style={{ width: `${homeWidth}%` }} /><i className={awayLead ? "lead statistic-away-bar" : "statistic-away-bar"} style={{ width: `${awayWidth}%` }} /></div></article>; }
function StatisticsPanel({ event }: { event: EventDetailEvent }) { const stats = event.detail?.statistics; if (!stats) return <EmptyDetailState text="暂无技术统计" />; const labels = event.sport === "football" ? footballStatLabels : basketballStatLabels; return <section className="statistics-panel">{labels.map(([key, label, percentage]) => { const value = stats[key]; return value ? <StatisticRow key={key} label={label} value={value} isPercentage={percentage} /> : null; })}</section>; }
function EmptyDetailState({ text }: { text: string }) { return <div className="event-detail-empty"><PlayIcon /><span>{text}</span></div>; }

function FormationRows({ players, formation, team }: { players: FootballPlayer[]; formation: string; team: "home" | "away" }) { const counts = formation.split("-").map(Number); let pointer = 1; const rows = [[players[0]], ...counts.map((count) => players.slice(pointer, pointer += count))]; return <div className={`football-formation ${team}`}>{rows.map((row, rowIndex) => <div className="football-line" key={rowIndex}>{row.map((player) => <FootballPlayerNode key={player.number} player={player} />)}</div>)}</div>; }
function FootballPlayerNode({ player }: { player: FootballPlayer }) { return <div className="football-player-node"><span className="player-number">{player.number}</span><PersonAvatar seed={player.seed} /><b title={player.name}>{player.name}</b></div>; }
function CoachCard({ name, coach, formation, side }: { name: string; coach: FootballTeamLineup["coach"]; formation: string; side: "home" | "away" }) { return <div className={`coach-card ${side}`}><span><b>{name}</b><small>阵型 {formation}</small></span><div><small>教练</small><strong>{coach.name}</strong></div><PersonAvatar seed={coach.seed} /></div>; }
function BenchList({ name, players }: { name: string; players: FootballPlayer[] }) { return <section className="bench-group"><h3>{name} 替补阵容</h3>{players.map((player) => <article className="bench-row" key={`${name}-${player.number}`}><b className="bench-number">{player.number}</b><PersonAvatar seed={player.seed} /><span><b>{player.name}</b><small>{player.position} · {player.value}</small></span>{player.substitutedAt && <em>{player.substitutedAt}</em>}</article>)}</section>; }
function FootballLineup({ event }: { event: EventDetailEvent }) { const lineup = event.detail?.footballLineup; if (!lineup) return <EmptyDetailState text="暂无阵容数据" />; return <section className="football-lineup"><div className="football-pitch" style={{ backgroundImage: `url(${asset("event-football-pitch.svg")})` }}><CoachCard name={event.away.name} coach={lineup.away.coach} formation={lineup.away.formation} side="away" /><FormationRows players={lineup.away.starters} formation={lineup.away.formation} team="away" /><FormationRows players={lineup.home.starters} formation={lineup.home.formation} team="home" /><CoachCard name={event.home.name} coach={lineup.home.coach} formation={lineup.home.formation} side="home" /></div><BenchList name={event.home.name} players={lineup.home.substitutes} /><BenchList name={event.away.name} players={lineup.away.substitutes} /></section>; }
function BasketballPlayerTable({ name, players }: { name: string; players: BasketballPlayer[] }) { return <section className="basketball-team"><h3>{name}</h3><div className="basketball-table-head"><span>球员</span><span>得分</span><span>篮板</span><span>助攻</span><span>投篮</span></div>{players.map((player) => <article className="basketball-player-row" key={`${name}-${player.number}`}><span className="basketball-player"><b>{player.number}</b><PersonAvatar seed={player.seed} /><em title={player.name}>{player.name}</em></span><span>{player.points}</span><span>{player.rebounds}</span><span>{player.assists}</span><span>{player.made}/{player.attempted}</span></article>)}</section>; }
function BasketballLineup({ event }: { event: EventDetailEvent }) { const lineup = event.detail?.basketballLineup; if (!lineup) return <EmptyDetailState text="暂无阵容数据" />; return <section className="basketball-lineup"><BasketballPlayerTable name={event.home.name} players={lineup.home} /><BasketballPlayerTable name={event.away.name} players={lineup.away} /></section>; }
function EventDetailTabs({ event }: { event: EventDetailEvent }) { const [tab, setTab] = useState<"statistics" | "timeline" | "lineup">("statistics"); return <section className="event-detail-tabs"><nav aria-label="赛事详情内容"><button className={tab === "statistics" ? "active" : ""} onClick={() => setTab("statistics")}>技术统计</button><button className={tab === "timeline" ? "active" : ""} onClick={() => setTab("timeline")}>赛况</button><button className={tab === "lineup" ? "active" : ""} onClick={() => setTab("lineup")}>阵容</button></nav>{tab === "statistics" ? <StatisticsPanel event={event} /> : tab === "timeline" ? <EmptyDetailState text="暂无赛况数据" /> : event.sport === "football" ? <FootballLineup event={event} /> : <BasketballLineup event={event} />}</section>; }

export function EventDetailPage({ event, onBack }: { event?: EventDetailEvent; onBack: () => void }) { if (!event) return <main className="event-detail-page"><header className="event-missing-header"><button aria-label="返回" onClick={onBack}><ArrowLeftIcon /></button></header><EmptyDetailState text="赛事不存在或已下线" /></main>; return <main className="event-detail-page"><EventVisualHeader event={event} onBack={onBack} /><EventDetailTabs event={event} /></main>; }
